### ISSUE TITLE
Using each frame's output for calcs and rendering pose

### ISSUE THREAD

**Issue by eledahl** [swittk/react-native-mlkit-pose-detection#1]
Hello there, great repo 

I'm trying to use it to convert over from tfjs/blazepose since I can record with react-native-vision-camera. Trying to understand how I can use the pose output to make calculations and render a pose on screen.

Here is the [example](https://github.com/tensorflow/tfjs-examples/blob/master/react-native/pose-detection/App.tsx#L299) of how they go about it. Just calling a function within the view will call it on each frame. It appears doing that with yours will just call the function once. Will this require creating a new plugin for the frame processor to work with the pose output and some native code or is there a way to use the output on each frame in the js?

**Comment by swittk** [comment]
Please refer to the code in the example app in the repo
https://github.com/swittk/react-native-mlkit-pose-detection/blob/9ecc85b22018f462b2180855893682eb6ee3182e/example/src/TestVisionCamera.tsx#L179

Then set the pose values to a state (e.g. useState()) and draw from there. That's how I use it.

Hope you find it useful,

Thanks.

**Comment by eledahl** [comment]
Hey thanks for getting back so quick.

Do you wrap it in `runonjs`?

I left out some important deets from my post. I've been using your example and had tried to `setPose` or run a different function in frameProcessor but get back `Tried to synchronously call function {bound dispatchSetState} from a different thread`

**Comment by eledahl** [comment]
Looks like `runOnJS(setPoses)(pose)` is the fix for me. Thanks again for responding!

**Comment by eledahl** [comment]
Hey @swittk, sorry to bug but how did you end up drawing your pose?

I ended up doing this for drawing:
```

const renderPose = () => {
    if (poses != null && poses.length > 0) {
      const selectedJoints = [
        poses[0].LeftShoulder,
        poses[0].RightShoulder,
        poses[0].LeftHip,
        poses[0].RightHip,
        poses[0].RightKnee,
        poses[0].LeftKnee,
        poses[0].RightAnkle,
        poses[0].LeftAnkle,
        poses[0].RightShoulder,
        poses[0].LeftToe,
        poses[0].RightToe,
        poses[0].RightElbow,
        poses[0].LeftElbow,
        poses[0].RightThumb,
        poses[0].LeftThumb,
      ]
        .filter((k) => (k.inFrameLikelihood ?? 0) > 0.3)
        .map((k, index) => {
          // Flip horizontally on android or when using back camera on iOS.
          return (
            <Svg >
              <Circle
                key={`skeletonkp_${k.type}`}
                cx={k.position.x}
                cy={k.position.y}
                r={25}
                strokeWidth="2"
                fill="transparent"
                stroke={Theme.COLORS.WHITE}
              />

              {/* <Circle
                key={`skeletonkp_${k.type}${index}`}
                cx={k.position.x}
                cy={k.position.y}
                r={10}
                strokeWidth="0"
                fill="#FAF9F6"
                stroke="transparent"
              /> */}
            </Svg>
          );
        });
      return (
        <Svg
          // height={Dimensions.get("window").height}
          // width={Dimensions.get("window").width}
          style={styles.svg}
          viewBox={getViewBox()}
        >
          {selectedJoints}
        </Svg>
      );
    } else {
      return <View></View>;
    }
  };

...
...
  svg: {
    position: "absolute",
    top: 0,
    left: 0,
    height: Dimensions.get("screen").height,
    width: Dimensions.get("screen").width,
    zIndex: 1,
}
```


Which worked fine on most phones but on an iphone pro max the pose is way too small compared to the body like this:

![IMG_0702](https://user-images.githubusercontent.com/47552416/234175475-7a1e1ff2-87f4-485d-87f3-e32bcd7ec011.PNG)

Aspect ratio of a pro max is 19.5:9 vs the normal 16:9. Did you ever encounter this issue?
